// 主页列表
export const ARTICLE_INDEX_LIST_KEY = 'ARTICLE_INDEX_LIST_KEY'
// 友情链接
export const FOOTER_LINK_LIST_KEY = 'FOOTER_LINK_LIST_KEY'
// 头部导航链接
export const HEADER_NAV_LINK_LIST_KEY = 'HEADER_NAV_LINK_LIST_KEY'
